# Remover esta linha:
# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Otimização: usar cached para melhor performance no macOS/Windows
      - ./:/var/www:cached
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Cache de vendor e node_modules para melhor performance
      - vendor_cache:/var/www/vendor
      - node_modules_cache:/var/www/node_modules
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy
    # Otimizações de recursos
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    # Otimizações de recursos
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    # Health check para melhor inicialização
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # Otimizações de recursos
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

volumes:
  dbdata:
    driver: local
  vendor_cache:
    driver: local
  node_modules_cache:
    driver: local

networks:
  laravel:
    driver: bridge